modules/admin/models/Users.php
<?php

namespace app\modules\admin\models;

use app\models\BaseModel;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\IdentityInterface;
use yii\base\Security;
/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property string $fullname
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $address
 */
class Users extends BaseModel implements IdentityInterface
{
    public $item_name;
    public $check_password;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['fullname', 'username', 'password', 'address'], 'required'],
            [['address'], 'string'],
            [['status'], 'integer'],
            [['email'], 'email'],
            [['created_at','created_by','updated_at','updated_by'], 'integer'],
            [['fullname'], 'string', 'max' => 100],
            [['username', 'password', 'email'], 'string', 'length' => [4,60]],
            [['username','email'], 'unique'],

        ];
    }
    public function afterFind()
    {
        $id = $this->id;
        $itemName = AuthAssignment::find()->where(['user_id' => $id])->asArray()->all();
        $this->item_name = ArrayHelper::getColumn($itemName,'item_name');
        return parent::afterFind();
    }
    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'fullname' => Yii::t('app', 'Full Name'),
            'username' => Yii::t('app', 'Username'),
            'password' => Yii::t('app', 'Password'),
            'email' => Yii::t('app', 'Email'),
            'status'=> Yii::t('app', 'Status'),
            'address' => Yii::t('app', 'Address'),

        ];
    }
    public function getUserRoles(){

    $depIds = self::find()
        ->select(['id'])
        ->where(['id' => $this->id])
        ->asArray()
        ->all();

    if(!empty($depIds)){

        $allIds = ArrayHelper::getColumn($depIds,'id');
        $departmentNames = AuthAssignment::find()
            ->select(['item_name'])
            ->where(['in','user_id', $allIds])
            ->asArray()
            ->all();
        $res = '';

        foreach ($departmentNames as $name){
            $res .= "<h6 class='badge badge-success' style='padding-bottom: 7px;'>{$name['item_name']}</h6>". " ";
        }

        return $res;
    }
    return null;
}
   public static function  getAssignment(){

        $model = AuthItem::find()->where(['type'=>1])->all();
        return ArrayHelper::map($model, 'name','name');
   }

    ////////////////////////////////////
    public static function findIdentity($id)
    {
        return self::findOne($id);
    }


    public static function findIdentityByAccessToken($token, $type = null)
    {

    }


    public static function findByUsername($username)
    {
        return self::findOne(['username' => $username]);
    }


    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        //  return $this->authKey;
    }


    public function validateAuthKey($authKey)
    {
        //  return $this->authKey === $authKey;
    }


    public function setPassword($password)
    {
        $this->password = Yii::$app->getSecurity()->generatePasswordHash($password);
    }

    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password);
    }

    public static function assignment2(){
        $client = AuthItem::find()->where(['type' => 1])
            ->asArray()
            ->all();
        return ArrayHelper::map($client, 'name' ,'name');
    }


}

modules/admin/controllers/UsersController.php
<?php

namespace app\modules\admin\controllers;

use app\controllers\BaseController;
use app\models\User;
use app\modules\admin\models\AuthAssignment;
use Yii;
use app\modules\admin\models\Users;
use app\modules\admin\models\AuthItem;
use app\modules\admin\models\UsersSearch;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends BaseController
{
    public function actionValidate()
    {
        $model = new Users();
        $request = \Yii::$app->getRequest();
        if ($request->isPost && $model->load($request->post())) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }
    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $users = Users::find()->orderBy(['id'=>SORT_DESC])->all();
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'users'=>$users,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if (Yii::$app->request->isAjax){
            return $this->renderAjax('view', [
                'model' => $this->findModel($id),
            ]);
        } else {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new Users model.
     * If creation is successful,
     * the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
         $model = new Users();
         $models = new AuthAssignment();
         $post = Yii::$app->request->post();
        if (Yii::$app->request->isPost) {
            try {
                $transaction = Yii::$app->db->beginTransaction();
            if ($model->load(Yii::$app->request->post())) {
                $model->setPassword($model->password);
                $model->save();
                $modelId = $model->id;
                $AuthAssignment = $post['Users']['item_name'];
                if (!empty($AuthAssignment)) {
                        $saved = true;
                        foreach ($AuthAssignment as $items) {
                            $add = new AuthAssignment();
                            $add->item_name = $items;
                            $add->user_id = $modelId;
                            if ($add->save()) {
                                $saved = true;
                            } else {
                                $saved = false;
                                break;
                            }
                        }

                        if ($saved) {
                            $transaction->commit();
                            Yii::$app->session->setFlash('success', 'Ma\'lumotlar saqlandi!');
                        } else {
                            $transaction->rollBack();
                            Yii::$app->session->setFlash('danger', 'Ma\'lumotlar saqlanmadi!');
                        }
                    }
                    return $this->redirect(['index']);
                }
            }catch (\Exception $e) {
                Yii::info('Error Data' . $e->getMessage(), 'save');
            }
        }
        if (Yii::$app->request->isAjax){
           return $this->renderAjax('create', [
                'model' => $model,
                'models' => $models,
            ]);
        }
        return $this->render('create', [
            'model' => $model,
            'models' => $models,
        ]);
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $post = Yii::$app->request->post();
        if (Yii::$app->request->isPost) {

                if ($model->load(Yii::$app->request->post())) {
                    if ((empty($post['new_password'])!=1)){
                        $model->password = Yii::$app->getSecurity()->generatePasswordHash($post['new_password']);
                    }
                    $model->save();
                    $modelId = $model->id;
                    $AuthAssignment = $post['Users']['item_name'];
                    try {
                        $transaction = Yii::$app->db->beginTransaction();
                if (!empty($AuthAssignment)) {
                    AuthAssignment::deleteAll(['user_id' => $modelId]);
                        $saved = true;
                        foreach ($AuthAssignment as $items) {
                            $add = new AuthAssignment();
                            $add->item_name = $items;
                            $add->user_id = $modelId;
                            if ($add->save()) {
                                $saved = true;
                            } else {
                                $saved = false;
                                break;
                            }
                        }

                        if ($saved) {
                            $transaction->commit();
                            Yii::$app->session->setFlash('success', 'Ma\'lumotlar saqlandi!');
                        } else {
                            $transaction->rollBack();
                            Yii::$app->session->setFlash('danger', 'Ma\'lumotlar saqlanmadi!');
                        }
                    }
                    return $this->redirect(['index']);
                }catch (\Exception $e) {
                        Yii::info('Error Data' . $e->getMessage(), 'save');
                    }
            }
        }
        if (Yii::$app->request->isAjax){
            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        AuthAssignment::deleteAll(['user_id'=>$id]);
        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
    public function actionUsername(){

        Yii::$app->response->format = Response::FORMAT_JSON;
        $response = [];
        $response['status'] = false;
        $id = Yii::$app->request->get('id');
        $username = Yii::$app->request->get('username');
        if ($id){
            $users = Users::find()->where(['username'=>$username])->andWhere(['not in','id', $id])->all();
        }else{
            $users = Users::find()->where(['username'=>$username])->all();
        }
        $response['message'] ;
        if(!empty($username) || !empty($email)){
            if (!empty($users)){
                $response['status'] = true;
                $response['data'] = $users;
                $response['message'] = 'OK';
            }
            else{
                $response['message'] = 'Empty';
                $response['data'] = Yii::$app->request->get();
            }
        }
        return $response;
    }
    public function actionEmail(){

        Yii::$app->response->format = Response::FORMAT_JSON;
        $response = [];
        $response['status'] = false;
        $id = Yii::$app->request->get('id');
        $email = Yii::$app->request->get('email');
        if ($id){
            $users = Users::find()->where(['email'=>$email])->andWhere(['not in','id', $id])->all();
        }else{
            $users = Users::find()->where(['email'=>$email])->all();
        }
        $response['message'] ;
        if(!empty($username) || !empty($email)){
            if (!empty($users)){
                $response['status'] = true;
                $response['data'] = $users;
                $response['message'] = 'OK';
            }
            else{
                $response['message'] = 'Empty';
                $response['data'] = Yii::$app->request->get();
            }
        }
        return $response;
    }
}

modules/admin/views/users/_form.php
<?php

use app\modules\admin\models\AuthItem;
use yii\helpers\Html;
use kartik\select2\Select2;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

//use yii\bootstrap\ActiveForm;
/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Users */
/* @var $form yii\widgets\ActiveForm */
/* @var $models */
/* @var $password */
?>

<?php $form = ActiveForm::begin([
    'id' => $model->formName(),
    'method' => 'post',
//     'enableAjaxValidation' => true,
//     'validationUrl' => Url::toRoute('users/validate'),
]); ?>

<?= $form->field($model, 'id')->hiddenInput(['maxlength' => true,'id'=>'id'])->label(false)?>
<?= $form->field($model, 'fullname')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'username')->textInput(['maxlength' => true,'id'=>'username']) ?>
<span class="offcanvas user_info" style="color: red"><?=Yii::t('app', 'This username has already been taken.');?></span>

<?php
if ($password == true) {
    ?>
    <a class="change_password" style="color: #0a73bb"><?=Yii::t('app', 'Change password');?></a><br>
    <label for="new_password" class="offcanvas label_pasword"><?=Yii::t('app', 'New password');?></label>
    <input type="password" id="new_password" class="offcanvas form-control" name="new_password"><br>

    <?php
} else { ?>
    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

<?php } ?>
<?= $form->field($model, 'email')->textInput(['id'=>'email','type'=>'email']) ?>
<span class="offcanvas user_email" style="color: red"><?=Yii::t('app', 'This email has already been taken.');?></span>

<?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'item_name')->widget(Select2::classname(), [
    'data' => $model::getAssignment(),
    'pluginOptions' => [
        'allowClear' => true,
        'multiple' =>true,
        'prompt' =>Yii::t('app', 'Select'),
    ],
])->label('Rules'); ?>
<?= $form->field($model, 'status')->dropDownList([
    $model::STATUS_ACTIVE => Yii::t('app', 'Active'),
    $model::STATUS_INACTIVE => Yii::t('app', 'Inactive'),
]); ?>


<?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-sm btn-outline-primary save_username']) ?>
<?php ActiveForm::end(); ?>
<br>

<?php
$url = Url::to(['username']);
$url1 = Url::to(['email']);
$js = <<< JS
$('body').delegate('.change_password', 'click', function(e) {
    e.preventDefault();
    $('#new_password').removeClass('offcanvas');
    $('.label_pasword').removeClass('offcanvas');
})
$(document).ready(function(e) {
        $('.modal-title').html('{$this->title}');
        $('.help-block').css({'color':'red'});
        
         
        $('#username').on('blur',function() {
           
          let  username = $(this).val(); 
          let  id = $('#id').val();
                $.ajax({
                    url:'{$url}',
                    type: 'GET',
                    data:{username:username,id:id},
                    success : function(response) {
                      if (response.status){
                          $('.save_username').prop('disabled',true);
                          $('.user_info').removeClass('offcanvas');
                      }else{
                          $('.save_username').prop('disabled',false);
                          $('.user_info').addClass('offcanvas');
                      }
                    }
                    
                })
        });
        $('#email').on('blur',function() {
           
          let  email = $(this).val(); 
          let  id = $('#id').val();
                $.ajax({
                    url:'{$url1}',
                    type: 'GET',
                    data:{email:email,id:id},
                    success : function(response) {
                      if (response.status){
                          $('.save_username').prop('disabled',true);                                
                          $('.user_email').removeClass('offcanvas');
                      }else{
                           $('.save_username').prop('disabled',false);
                          $('.user_email').addClass('offcanvas');
                      }
                    }
                    
                })
        });
        
});
JS;
$this->registerJs($js);

$css = <<<CSS
        .select2-container--krajee .select2-selection--multiple .select2-selection__choice{
           background-color: #0a73bb;
           color: white;
        }
       
CSS;
$this->registerCss($css)

?>

modules/admin/views/users/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\UsersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'fullname') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'stratus') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/users/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Users */
/* @var $models app\modules\admin\models\AuthAssignment */

$this->title = Yii::t('app', 'Create user');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

    <?= $this->render('_form', [
        'model' => $model,
        'models' =>$models,
        'password' => false
    ]) ?>


<?php
$js = <<< JS
$(document).ready(function(e) {
        $('.modal-title').html('{$this->title}');
});
JS;
$this->registerJs($js)
?>

modules/admin/views/users/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\UsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>

    <button class="offcanvas" id="kt_quick_cart_toggle"></button>
    <!--begin::Card-->
    <div class="card card-custom">
        <div class="card-header flex-wrap border-0 pt-6 pb-0">
            <div class="col-lg-9 col-xl-8" style="padding: 0px!important;">

            </div>
            <div class="card-toolbar">
                <!--begin::Button-->
                <a href="<?=\yii\helpers\Url::to(['users/create'])?>" class="btn btn-sm btn-primary font-weight-bolder create-click">
                    <span class="svg-icon svg-icon-md">
                        <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                        <svg xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                             height="24px" viewBox="0 0 24 24" version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <rect x="0" y="0" width="24" height="24"/>
                                <circle fill="#000000" cx="9" cy="15" r="6"/>
                                <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z"
                                      fill="#000000" opacity="0.3"/>
                            </g>
                        </svg>
                        <!--end::Svg Icon-->
                    </span><?=Yii::t('app', 'Create')?></a>
                <!--end::Button-->
            </div>
        </div>
        <div class="separator separator-solid"></div>
        <div class="card-body">
            <? $form = \yii\bootstrap\ActiveForm::begin(); ?>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'summary' => '',
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    'fullname',
                    'username',
                    [
                        'attribute' => 'status',
                        'format' => 'raw',
                        'value' => function ($model) {
                            if ($model->status == $model::STATUS_ACTIVE) {
                                return "<span class='badge badge-info'>Active</span>";
                            } else {
                                return "<span class='badge badge-warning'>Inactive</span>";
                            }
                        }
                    ],
                    [
                        'attribute' => 'id',
                        'format' => 'html',
                        'label' =>Yii::t('app', 'Roles'),
                        'value' => function ($model) {
                            return $model->getUserRoles();
                        }
                    ],

                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{view} {update} {delete}',
                        'header' => Yii::t('app', "Action"),
                        'options' => ['style' => '140px;'],
                        'buttons' => [
                            'view' => function ($url) {
                                return '<a href="' . $url . '" class="btn btn-outline-info btn-xs view-modal-show" data-toggle="modal" data-target="#exampleModalCustomScrollable"><i class="la la-eye ml-1"></i></a>';
                            },
                            'delete' => function ($url) {
                                return '<a href="' . $url . '" class="btn btn-outline-danger btn-xs" ><i class="la la-trash ml-1"></i></a>';
                            },
                            'update' => function ($url) {
                                return '<a href="' . $url . '" class="btn btn-outline-primary btn-xs click-button-update"><i class="la la-pencil ml-1"></i></a>';
                            }
                        ]
                    ],
                ],
            ]); ?>
            <input type="submit" class="offcanvas click-button-ajax">
            <? \yii\bootstrap\ActiveForm::end(); ?>

        </div>
    </div>
<button id="kt_demo_panel_toggle" class="offcanvas"></button>
<?php
$js = <<<JS
  $('.create-click').click(function(e) {
        e.preventDefault();
        let url=$(this).attr('href');
        $('#kt_quick_cart_toggle').click();
        $('.create-modal').html(''); 
        $('.create-modal').load(url); 
  });

    $('body').delegate('.click-button-update', 'click', function(e) {
        e.preventDefault();
        let url = $(this).attr('href');
        $('#kt_quick_cart_toggle').click();
        $('.create-modal').html('');
        $('.create-modal').load(url);
        
    });
    
JS;
$this->registerJs($js, \yii\web\View::POS_END);

modules/admin/views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Users */

$this->title = Yii::t('app', 'Update Users: {name}', [
    'name' => $model->fullname,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
    <?= $this->render('_form', [
        'model' => $model,
        'password' => true
    ]) ?>


<?php
$js = <<< JS
$(document).ready(function(e) {
        $('.modal-title').html('{$this->title}');
});
JS;
$this->registerJs($js)
?>

modules/admin/views/users/view.php
<?php

use app\modules\admin\models\Users;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Users */

$this->title = $model->fullname;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="users-view">
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'fullname',
            'username',
          //'password',
            'email:email',
            'address',
            'status',
            [
                'attribute' => 'created_by',
                'value' => function ($model) {
                    return !empty(Users::findOne($model->created_by))
                        ? Users::findOne($model->created_by)->fullname . "<br><small>
                    <p style='font-size: small; color: green'>" . date('d.m.Y H:i', $model->created_at) . "</p></small>"
                        : $model->created_by;
                },
                'format' => 'raw'
            ],
            [
                'attribute' => 'updated_by',
                'value' => function ($model) {
                    return (Users::findOne($model->updated_by))
                        ? Users::findOne($model->updated_by)->fullname . "<br><small>
                    <p style='font-size: small; color: red'>". date('d.m.Y H:i', $model->updated_at) . "</p></small>"
                        : $model->updated_by;
                },
                'format' => 'raw'
            ],
        ],
    ]) ?>
    <p>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-sm btn-outline-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Вы уверены, что хотите удалить этот элемент?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

</div>

<?php
$js = <<< JS
$(document).ready(function(e) {
        $('.modal-title').html('{$this->title}');
});
JS;
$this->registerJs($js)
?>