modules/manufactures/controllers/ProductionController.php
<?php

namespace app\modules\manufactures\controllers;

use app\modules\manufactures\models\ProductionItem;
use app\modules\manufactures\models\Recipe;
use app\modules\manufactures\models\RecipeIngredient;
use app\modules\warehouse\models\ItemBalance;
use Yii;
use app\modules\manufactures\models\Production;
use app\modules\manufactures\models\ProductionSearch;
use app\controllers\BaseController;
use yii\db\Exception;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * ProductionController implements the CRUD actions for Production model.
 */
class ProductionController extends BaseController
{

    /**
     * Lists all Production models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Production model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = Production::getProductModel($id);
        $models = Production::getProductItemModels($id);
        return $this->render('view', [
            'model' => $model,
            'models' => $models
        ]);
    }

    /**
     * Creates a new Production model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Production();
        if (Yii::$app->request->isPost) {
            $data = Yii::$app->request->post();
            $model->status = $model::STATUS_ACTIVE;
            try {
                $transaction = Yii::$app->db->beginTransaction();
                $saved = false;
                if ($model->load($data) && $model->save()) {
                    $producId = $model->id;
                    $saved = true;
                    if (!empty($data['ProductionItem'])) {
                        $saved = false;
                        foreach ($data['ProductionItem'] as $product) {
                            $modelProItem = new ProductionItem();
                            $modelProItem->setAttributes([
                                'production_id' => $producId,
                                'recipe_ingredient_id' => $product['recipe_production_id'],
                                'quantity' => $product['quantity'],
                                'wasting_percent' => $product['wasting_percent'],
                                'status' => $model::STATUS_ACTIVE
                            ]);
                            if ($modelProItem->save()) {
                                $saved = true;
                            } else {
                                $saved = false;
                                break;
                            }
                        }
                    }
                    if ($saved) {
                        $transaction->commit();
                        Yii::$app->session->setFlash('success', "Saved SuccessFully");
                        return $this->redirect(['view', 'id' => $model->id]);
                    } else {
                        $transaction->rollBack();
                    }
                }
            } catch (Exception $e) {
                Yii::info('Error Document ' . $e->getMessage(), 'save');
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Production model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $lang = Yii::$app->language;
        $model = $this->findModel($id);
        $responseble = Production::getResponsebles($model->department_id,0);
        $responseble = ArrayHelper::map($responseble,'id','name');
        $sql = "SELECT
                   pi.id AS production_id,
                   ri.id as item_id,
                   CONCAT(item.name_{$lang} , '/', item.article) AS name,
                   r.name_{$lang} AS unit,
                   pi.quantity,
                   pi.wasting_percent,
                   CASE WHEN ib.price IS NULL THEN 0
                   ELSE ib.price END AS price
                FROM production_item AS pi
                LEFT JOIN recipe_ingredient as ri ON pi.recipe_ingredient_id = ri.id
                LEFT JOIN item ON item.id = ri.item_id
                LEFT JOIN public.references AS r ON item.unit_id = r.id
                LEFT JOIN public.item_balance AS ib ON ib.item_id = ri.item_id 
                AND  ib.department_id = {$model->department_id}
                AND ib.department_area_id = {$model->department_area_id}
                WHERE pi.production_id = {$id}/*
                AND ib.id in (SELECT MAX(ib2.id) as id FROM item_balance as ib2 
                GROUP BY ib2.item_id ,
                ib2.price,ib2.department_area_id);*/";
        $models = Yii::$app->db->createCommand($sql)->queryAll();
        if (Yii::$app->request->isPost) {
            $data = Yii::$app->request->post();
            $model->status = $model::STATUS_ACTIVE;
            try {
                $transaction = Yii::$app->db->beginTransaction();
                $saved = false;
                if ($model->load($data) && $model->save()) {
                    $producId = $model->id;
                    $saved = true;
                    if (!empty($data['ProductionItem'])) {
                        $saved = false;
                        ProductionItem::deleteAll(['production_id' => $id]);
                        foreach ($data['ProductionItem'] as $product) {
                            $modelProItem = new ProductionItem();
                            $modelProItem->setAttributes([
                                'production_id' => $producId,
                                'recipe_ingredient_id' => $product['recipe_production_id'],
                                'quantity' => $product['quantity'],
                                'wasting_percent' => $product['wasting_percent'],
                                'status' => $model::STATUS_ACTIVE
                            ]);
                            if ($modelProItem->save()) {
                                $saved = true;
                            } else {
                                $saved = false;
                                break;
                            }
                        }
                    }
                    if ($saved) {
                        $transaction->commit();
                        Yii::$app->session->setFlash('success', "Saved SuccessFully");
                        return $this->redirect(['view', 'id' => $model->id]);
                    } else {
                        $transaction->rollBack();
                    }
                }
            } catch (Exception $e) {
                Yii::info('Error Document ' . $e->getMessage(), 'save');
            }

        }
        return $this->render('update', [
            'model' => $model,
            'models' => $models,
            'responseble' => $responseble,
        ]);
    }


    /**
     * Deletes an existing Production model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if (!empty($model))
        {
            $model->status = $model::STATUS_DELETED;
            $sql = "UPDATE production_item
                    SET status = %d WHERE production_id = %d;";
            $sql = sprintf($sql,$model::STATUS_DELETED,$model->id);
            $result = Yii::$app->db->createCommand($sql)->queryAll();
            if ($model->save() && $result) {
                return $this->redirect(['index']);
            }else {
                return $this->redirect(Yii::$app->request->referrer);
            }
        }
    }

    public function actionSaveAndFinish($id){

        $production = Production::findOne($id);
        if (!empty($production)) {
            $production_item = ProductionItem::find()->where(['production_id' => $production['id']])->asArray()->all();
            $dep = $production->department_id;
            $dep_area = $production->department_area_id;
            $reg_date=$production->reg_date;
            $recipe_id = Recipe::findOne($production['recipe_id'])->item_id;
            $productionId = $id;$summ=0;
            try {
                $transaction = Yii::$app->db->beginTransaction();
                $saved = false;
                if (!empty($production_item)) {
                    $saved = true;
                    foreach ($production_item as $item) {
                        $saved = false;
                        $item_id = RecipeIngredient::findOne($item['recipe_ingredient_id'])->item_id;
                        $sql = "SELECT ib.* FROM item_balance AS ib
                                    INNER JOIN (SELECT MAX(id) AS id FROM item_balance
                                    GROUP BY item_id, price,department_area_id,department_id
                                    ORDER BY id DESC) AS ib2 ON ib2.id = ib.id
                                    LEFT JOIN (SELECT MIN(ib.id) AS id, sum(inventory) AS summa FROM item_balance AS ib
                                        INNER JOIN (SELECT MAX(id) AS id FROM item_balance

modules/manufactures/views/production/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\manufactures\models\ProductionSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="production-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'recipe_id') ?>

    <?= $form->field($model, 'reg_date') ?>

    <?= $form->field($model, 'quantity') ?>

    <?= $form->field($model, 'wasted_quantity') ?>

    <?php // echo $form->field($model, 'department_id') ?>

    <?php // echo $form->field($model, 'department_area_id') ?>

    <?php // echo $form->field($model, 'responsible') ?>

    <?php // echo $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'additional_price_percent') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/manufactures/views/production/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\manufactures\models\Production */

$this->title = Yii::t('app', 'Create Production');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Productions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="production-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/manufactures/views/production/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\modules\manufactures\models\ProductionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Productions');
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
    .twoInOne{
        font-size: 10px;
        border-top: grey 1px solid;
        display: block;
    }
    .new-row {
        display: block;
    }
</style>
<div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
        </div>
        <div class="card-toolbar">
            <a href="<?= Url::to(['production/create']) ?>" class="btn btn-sm btn-primary">
                        <span class="svg-icon svg-icon-md">
                        <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                        <svg xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                             height="24px" viewBox="0 0 24 24" version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <rect x="0" y="0" width="24" height="24"/>
                                <circle fill="#000000" cx="9" cy="15" r="6"/>
                                <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z"
                                      fill="#000000" opacity="0.3"/>
                            </g>
                        </svg>
                            <!--end::Svg Icon-->
                    </span><?=Yii::t('app', 'Create')?>
            </a>
            <!--end::Button-->
        </div>
    </div>
    <div class="card-body">
        <!--begin: Search Form-->
        <?php if (Yii::$app->session->hasFlash('danger')): ?>
            <h6 class="alert alert-danger"><?=Yii::$app->session->getFlash('danger'); ?></h6>
        <?php elseif (Yii::$app->session->hasFlash('success')): ?>
            <h6 class="alert alert-success"><?=Yii::$app->session->getFlash('success'); ?></h6>
        <?php endif; ?>
        <!--begin::Search Form-->
        <!--end::Search Form-->
        <? $form = \yii\bootstrap\ActiveForm::begin(); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'summary' => '',
            'columns' => [
                [
                    'class' => 'yii\grid\SerialColumn',
                    'options' => ['style' => 'width:40px'],
                ],

                'recipe_id',
                'quantity',
                'wasted_quantity',
                'department_id',
                'department_area_id',
                [
                    'attribute' => 'created_by',
                    'format' => 'raw',
                    'value' => function($model){
                        return "<span class='new-row'>{$model->responsible0->fullname}</span><span class='twoInOne'>".date('Y-m-d H:i:s', $model->created_at)."</span>";
                    }
                ],
                'additional_price_percent',

                [
                    'class' => 'yii\grid\ActionColumn',
                    'header' => Yii::t('app', "Action"),
                    'template' => '{view} {update} {delete}',
                    'options' => ['style' => 'width:100px;'],
                    'buttons' => [
                        'view' => function($url, $model){
                            return '<a href="'.Url::to(['production/view', 'id' => $model->id]).'" class="btn btn-xs btn-outline-info" ><i class="la la-eye ml-1"></i></a>';
                        },
                        'delete' => function($url, $model){
                            return '<a href="'.Url::to(['production/delete', 'id' => $model->id]).'" class="btn btn-xs btn-outline-danger" ><i class="la la-trash ml-1"></i></a>';
                        },

                        'update' => function($url, $model){
                            return '<a href="'.Url::to(['production/update', 'id' => $model->id]).'" class="btn btn-xs btn-outline-primary"><i class="la la-pencil ml-1"></i></a>';
                        }
                    ],
                    'visibleButtons' => [
                        'update' => function($model) {
                            return ($model->status == 1 || $model->status == 2);
                        },
                        'delete' => function($model) {
                            return ($model->status == 1 || $model->status == 2);
                        },
                        'view' => function($model) {
                            return true;
                        },
                    ],
                ],
            ],
        ]); ?>
        <input type="submit" class="offcanvas click-button-ajax">
        <? \yii\bootstrap\ActiveForm::end(); ?>
    </div>
</div>
<button id="kt_quick_panel_toggle" class="offcanvas">

</button>
<?php
$js = <<<JS
 
 
JS;
$this->registerJs($js);

?>

modules/manufactures/views/production/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\manufactures\models\Production */
/* @var $models app\modules\manufactures\models\ProductionItem */
/* @var $responseble */

$this->title = Yii::t('app', 'Update Production: {name}', [
    'name' => $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Productions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
    <?= $this->render('_form', [
        'model' => $model,
        'models' => $models,
        'responseble' => $responseble,
    ]) ?>
<?php
$js = <<<JS
$('#department_area_id').prop("disabled", false); 
$('#recipe').prop("disabled", false); 
JS;
$this->registerJs($js);

modules/manufactures/views/production/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\manufactures\model\Production */
/* @var $models app\modules\manufactures\model\ProductionItem */

$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Productions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
//echo "<pre>";
//    print_r($models);
//echo "</pre>";exit();
?>

    <div class="tovar-form">
        <div class="card card-custom gutter-b example example-compact">
            <div class="card-header mt-5">
                <div class="col-xs-8">
                    <h4><?=Yii::t('app','Document Number:'); ?> <?= Html::encode($this->title) ?></h4>
                </div>
                <div class="col-xs-4 text-right">
                    <a href="<?= \yii\helpers\Url::to(['production/index']) ?>"
                       class="btn btn-sm btn-outline-primary font-weight-bolder">
                        <i class="la la-backspace"></i><?= Yii::t('app', 'Назад'); ?>
                    </a>
                </div>
                <?php if ($model['status'] == '1'): ?>
                    <div class="col-sm-12 mb-4 mt-4">
                        <a class=" btn btn-sm btn-success" href="<?=\yii\helpers\Url::to(['production/save-and-finish', 'id' => $model['id']])?>"><?=Yii::t('app', 'Save And Finish'); ?></a>
                        <a class="ml-2 btn btn-sm btn-outline-primary" href="<?=\yii\helpers\Url::to(['production/update', 'id' => $model['id']])?>"><?=Yii::t('app', 'Update'); ?></a>
                        <?php
                        echo Html::a(Yii::t('app', 'Delete'), \yii\helpers\Url::to(['delete', 'id' => $model['id']]), [
                            'class' => "ml-2 btn btn-sm btn-outline-danger",
                            'data' => [
                                'confirm' => Yii::t('app', 'Вы уверены, что хотите удалить этот элемент?'),
                                'method' => 'POST',
                            ],
                        ]);
                        ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="card-body">
                <table class="production-table">
                    <thead >
                    <tr>
                        <th><b><?=Yii::t('app', 'Recipe:'); ?></b> <span><?=!empty($model['item_name']) ? $model['item_name'] : NULL;?></span></th>
                        <th><b><?=Yii::t('app', 'Reg date:')?></b> <span><?=$model['reg_date']; ?></span></th>
                    </tr>
                    <tr>
                        <th><b><?=Yii::t('app', 'Department:')?></b> <span><?=$model['dep_name']; ?></span></th>
                        <th><b><?=Yii::t('app', 'Department Area:')?></b><span><?=!empty($model['dep_area_name']) ? $model['dep_area_name']: NULL ;?></span></th>
                    </tr>
                    <tr>
                        <th><b><?=Yii::t('app', 'Quantity:'); ?></b> <span><?=!empty($model['quantity']) ? $model['quantity'] : NULL ;?></span><span><?=!empty($model['unit']) ? $model['unit'] : NULL ;?></span></th>
                        <th><b><?=Yii::t('app', 'Wasted Quantity:')?></b> <span><?=!empty($model['wasted_quantity']) ? $model['wasted_quantity'] : NULL ;?></span></th>
                    </tr>
                    </thead>
                </table>
                <table class="models-table">
                    <thead>
                    <tr class="models-tr">
                        <th>#</th>
                        <th><?=Yii::t('app', 'Item'); ?></th>
                        <th><?=Yii::t('app', 'To Department Area'); ?></th>
                        <th><?=Yii::t('app', 'Quantity')?></th>
                        <th><?=Yii::t('app', 'Wasting percent')?></th>
                        <th><?=Yii::t('app', 'Jami:')?></th>
                    </tr>
                    </thead>
                    <tbody class="models-tbody">
                    <?php $i = 1;?>
                    <?php foreach ($models as $key) : ?>
                        <tr class="item-tbody-tr">
                            <td><?=$i++; ?></td>
                            <td><span><?=$key['name'] ?? NULL;?></span></td>
                            <td><span><?=$model['dep_area_name'] ?? NULL;?></span></td>
                            <td class="quantity"><span><?=$key['quantity'] ?? NULL;?></span>&nbsp;&nbsp;&nbsp;<span><?=$key['unit'] ?? NULL;?></span></td>
                            <td><span><?=$key['wasting_percent'] ?? NULL;?></span></td>
                            <td><span><?=($key['quantity'] * (1-$key['wasting_percent']/100)) ?? NULL;?></span></td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
<?php
$css = <<< CSS
    .models-table {
        margin-top: 20px;
        font-family: Arial;
    }
    .models-table th {
        border: 1px solid gray;
    }
    .production-table th {
        border: 1px solid slategrey;
        padding-left: 10px;
    }
    .models-tr th {
        padding-left: 5px;
        background-color: #0c5460;
        color: whitesmoke;
    }
    .models-tbody-tr td {
        border: 1px solid black;
        padding-left: 5px;
    }
    .footer-out td {
        border: 1px solid slategrey;
        padding-right: 5px;
        color: #0a73bb;
    }
    th span {
        color: gray;
        margin-left: 8px;
    }
    tr {
      height: 30px;
    }
    table {
      width: 100%;
    }
    hr {
        background-color: #0c5460;
        height: 2px;
    }
CSS;
$this->registerCss($css);